### ISSUE TITLE
Basics of Check My Work

### ISSUE THREAD

**Issue by carolinapowers** [pluralsight-projects/Angular-AlbumStoreProductPage#12]
Adding it here, but I also added it to our spread sheet.

Carolina - I think we are missing or not highlighting enough a crucial part of Projects which is having the user adding, committing and pushing their code prior to clicking Check My Work. I think we need to emphasize and remind the user of that. I'm not sure if I came across that information in anywhere.

**Comment by adamfortuna** [comment]
Carolina - I'm going to close this one here to make sure Jon isn't solving it only in the existing framework (ie, by changing tasks). This seems like a change to the overall product to change this process. If you're thinking this could be done by making content changes to tasks or the task group header part, we could keep this one open though as a recommendation (let me know if thats what you're thinking).
