### ISSUE TITLE
Part 1 Task 4

### ISSUE THREAD

**Issue by carolinapowers** [pluralsight-projects/Angular-AlbumStoreProductPage#13]
When submitting tasks one at a time, Task 4 will throw a non-custom message when the previous task was correct and task 4 isn't yet.

![image](https://user-images.githubusercontent.com/10137641/31245755-552f5fa0-a9d9-11e7-8313-88a9194d7c94.png)

**Comment by jonfriskics** [comment]
Should be good now.
