### ISSUE TITLE
Code being overwritten by Angular?

### ISSUE THREAD

**Issue by carolinapowers** [pluralsight-projects/Angular-AlbumStoreProductPage#15]
Not sure if it's if the issue is with the Angular project or with tutor...

But, I tested submitting a task when it was wrong and I got one error message. I solved that message, but did not submit a complete correct answer again. So, I got the second error message.
Once I solved that and submitted the correct code, the task does not validate my answer. It looks like it's overwritten somewhere in Angular.

![image](https://user-images.githubusercontent.com/10137641/31247319-2967c81c-a9de-11e7-9d99-0e182f4a02aa.png)
 

This task should pass now:

![image](https://user-images.githubusercontent.com/10137641/31247492-c4719518-a9de-11e7-9cea-cc8cb2969e20.png)

![image](https://user-images.githubusercontent.com/10137641/31247591-0db5046c-a9df-11e7-8473-dae777d50fa1.png)

**Comment by jonfriskics** [comment]
based on your code here, it looks like the error is that you are setting your widht to `100` but the task is looking for `100%`.  I believe just setting to `100` will default to `100px`, not percentages.

**Comment by carolinapowers** [comment]
Just saw that and was going to delete it. ;)
