### ISSUE TITLE
NPM install not working

### ISSUE THREAD

**Issue by kingmathers92** [pluralsight-projects/Angular-AlbumStoreProductPage#153]
I run npm install on git bash and i don't see the progress, I see the node_modules folder created but as soon as it finishes "packaging" the folder disappears. I tried in the vs code terminal, I started seeing the packaging progress bar but same result at the end:(

**Comment by kingmathers92** [comment]
I found the solution for windows:
`npm install --legacy-peer-deps`
That will tell NPM to ignore peer deps and proceed with the installation anyway.

**Comment by IEdiong** [comment]
I tried this and it did not seem to work for me. Any other solution?

**Comment by oluwaGamer** [comment]
This solution worked for me.
