### ISSUE TITLE
Allow flexible whitespace when using regex to in testing

### ISSUE THREAD

**Issue by adamfortuna** [pluralsight-projects/Angular-AlbumStoreProductPage#19]
From @mikemike26 

> Mike - Consider lightening the white space linting.  It currently doesn't allow for new lines between methods or code blocks.

**Comment by jonfriskics** [comment]
pairing w/Mike on this next week.

**Comment by jonfriskics** [comment]
for the whitespace part of this one - https://github.com/pluralsight-projects/Angular-AlbumStoreProductPage/commit/e7d0e23eb9a8810ab4acaabfebee71ad946ae2ae

**Comment by jonfriskics** [comment]
closed with 8255d7dd453bcf526114a0cddf60e66d951371a9 and 0a517b8ac62d3d43f655100813690a61c858634f
