### ISSUE TITLE
Test fails when linter formats correct code

### ISSUE THREAD

**Issue by carolinapowers** [pluralsight-projects/Angular-AlbumStoreProductPage#29]
Part 3 task 12 fails if user submits code formatted by linter:

It will accept this code inside `product-description-component.ts`:
```
  ngOnInit() {
    this._productService.getAlbum(1).subscribe(response => this.albumInfo = response);
  }
```
But it will fail with this code:

```
  ngOnInit() {
    this._productService
      .getAlbum(1)
      .subscribe(response => (this.albumInfo = response));
  }
```

![image](https://user-images.githubusercontent.com/10137641/32614912-4b3cd56c-c53c-11e7-9961-f514c5a3d68f.png)

**Comment by carolinapowers** [comment]
The same happens on Part 4 task 8:

In `product.service.ts`, the formatted code will fail:

```

  getAlbum(id: number): Observable<Album> {
    return this._http
      .get(this._albumUrl)
      .map(response => <Album>response.json());
  }
```
This code will pass:

```
  getAlbum(id: number): Observable<Album> {
    return this._http.get(this._albumUrl).map(response => <Album>response.json());
  }
```

![image](https://user-images.githubusercontent.com/10137641/32620167-fcff800c-c54a-11e7-8f31-c8aba339e352.png)

**Comment by jonfriskics** [comment]
this is related to RegEx tests for those two challenges.  I can make some changes.

**Comment by carolinapowers** [comment]
Yeah,  I figured they were... 😄  . Not sure if you took a look at the Angular2 course sandbox. I believe there were methods in there that allowed you to get AST's instead of relying on RegEx for everything. 

https://github.com/codeschool/AcceleratingThroughAngular2Course/blob/master/accelerating_through_angular/levels/level2/section1/conditionals.rb

**Comment by jonfriskics** [comment]
I did, but it was taking me too long to figure out how to extract the useful parts and figure out how to make it all work so at one point I switched to what I knew i could make work.

Longer term it would be cool to have a team to work on tools like that for authors.

**Comment by jonfriskics** [comment]
I believe I've got all these fixed in https://github.com/pluralsight-projects/Angular-AlbumStoreProductPage/commit/b0bb0177e5df45b39043d8e0306818ba5b1b4573 and https://github.com/pluralsight-projects/Angular-AlbumStoreProductPage/commit/845334f651f48c5479e463b5722192e2f40c17cd

**Comment by codacy20** [comment]
sorry but it's not working for me, with the new regex code.

**Comment by codacy20** [comment]
@jonfriskics

**Comment by codacy20** [comment]
@jonfriskics Never mind, i ended up copying someone else code. The issue was that i wrote my code in two lines instead of one.
