### ISSUE TITLE
Add Subproject taskgroup descriptions for each subproject

### ISSUE THREAD

**Issue by adamfortuna** [pluralsight-projects/Angular-AlbumStoreProductPage#8]
At the top of this page, there's a place to add a line of text that shows up in a box at the top of the page. (like the prototype screenshot below). You can add these per-task group.

We'll want to go through and add these for each task group, with the command to run tests for that grouping and any other information you want to convey.

<img width="1249" alt="screen shot 2017-10-05 at 1 20 46 pm" src="https://user-images.githubusercontent.com/7741/31240861-0ae811c0-a9d0-11e7-91d0-2c7d9eda0522.png">

<img width="1009" alt="screen shot 2017-10-05 at 1 19 18 pm" src="https://user-images.githubusercontent.com/7741/31240867-0d728376-a9d0-11e7-8987-094b480b68d4.png">

## Add theses for all parts

* [x] Part 1
* [ ] Part 2
* [ ] Part 3
* [ ] Part 4
* [ ] Part 5
* [ ] Part 6

**Comment by jonfriskics** [comment]
went to add this but found it was already here 😄
