### ISSUE TITLE
Add answer video timing for all tasks

### ISSUE THREAD

**Issue by adamfortuna** [pluralsight-projects/Angular-AlbumStoreProductPage#9]
This is something down the line after we get any additional assets from Sams team, but wanted to make sure we had an issue for it here:

- [x] Part 1
- [x] Part 2
- [x] Part 3
- [x] Part 4
- [x] Part 5
- [x] Part 6

**Comment by jonfriskics** [comment]
times are in there now, but leaving this open pending the `youtube_video_id` conversation w/Meg.

**Comment by jonfriskics** [comment]
this is all good now.
